[package]
name = "rnbook"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
colored = "3.0.0"
crossterm = "0.28.1"
dirs = "6.0.0"
serde = {version = "1.0.218", features = ["derive"] } 
serde_json = { version = "1.0.139" }

[profile.release]
debug = true
